version: '3'

services:

  mongo:
    image:
      mongo:4.2
    container_name:
      jp-main-site-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGODB_USER="user"
      - MONGODB_PASS="password"
    volumes:
      - .docker-data/mongo:/data/db
    ports:
      - "27017:27017"
    command:
      mongod
